name: Build PDF Auto-Sender

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Firefox manually
      run: |
        Invoke-WebRequest "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US" -OutFile firefox.exe
        Start-Process -Wait -FilePath .\firefox.exe -ArgumentList "/S"
        Remove-Item firefox.exe

    - name: Install GeckoDriver
      run: |
        $geckoVersion = (Invoke-RestMethod "https://api.github.com/repos/mozilla/geckodriver/releases/latest").tag_name
        Invoke-WebRequest "https://github.com/mozilla/geckodriver/releases/download/$geckoVersion/geckodriver-$geckoVersion-win64.zip" -OutFile geckodriver.zip
        Expand-Archive geckodriver.zip -DestinationPath .
        Rename-Item geckodriver.exe geckodriver.exe

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==5.13.0

    - name: Build executable
      run: |
        pyinstaller --onefile --name PDFService `
          --add-data "geckodriver.exe;." `
          --add-data "sms;sms" `
          --add-data "whatsapp;whatsapp" `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFService-Package
        path: |
          dist/PDFService.exe
          geckodriver.exe
