name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome
      run: |
        choco install googlechrome -y
        refreshenv

    - name: Install ChromeDriver
      run: |
        $chromeVersion = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)'
        $version = (Get-Item $chromeVersion).VersionInfo.ProductVersion
        $majorVersion = $version.Split('.')[0]
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$majorVersion" -OutFile version.txt
        $driverVersion = Get-Content version.txt
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$driverVersion/chromedriver_win32.zip" -OutFile chromedriver.zip
        Expand-Archive chromedriver.zip -DestinationPath .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==5.13.0

    - name: Build executable
      run: |
        pyinstaller --onefile --name PDFSender `
          --add-data "chromedriver.exe;." `
          --add-data "sms;sms" `
          --add-data "whatsapp;whatsapp" `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFSender
        path: |
          dist/PDFSender.exe
          chromedriver.exe
