name: Build PDF Auto-Sender Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Firefox
      uses: GabrielBB/setup-firefox@v1
      with:
        firefox-version: 'latest'

    - name: Install GeckoDriver
      uses: nanasess/setup-geckodriver@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==5.13.0

    - name: Build executable
      run: |
        pyinstaller --onefile --name PDFService `
          --add-data "geckodriver.exe;." `
          --add-data "sms;sms" `
          --add-data "whatsapp;whatsapp" `
          --hidden-import selenium.webdriver.firefox.service `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFService-Package
        path: |
          dist/PDFService.exe
          geckodriver.exe
