name: CI/CD Pipeline

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install Chrome
      uses: actions/setup-chrome@v2
      with:
        chrome-version: 'stable'

    - name: Auto Install ChromeDriver
      run: |
        $chromeVersion = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo.ProductVersion
        $driverVersion = (Invoke-RestMethod "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$($chromeVersion.Split('.')[0..2] -join '.')")
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$driverVersion/chromedriver_win32.zip" -OutFile chromedriver.zip
        Expand-Archive chromedriver.zip -DestinationPath .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==5.13.0

    - name: Build executable
      run: |
        pyinstaller --onefile --name PDFSender `
          --add-data "chromedriver.exe;." `
          --add-data "sms;sms" `
          --add-data "whatsapp;whatsapp" `
          --hidden-import watchdog.events `
          main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFSender-Package
        path: |
          dist/PDFSender.exe
          chromedriver.exe
          sms/
          whatsapp/
